using MCD2.Installer;
using System.IO.Compression;
using System.Text;
using System.Text.Json;
int cases=0;
void Check(bool b,string name){if(!b)throw new Exception(name);cases++;Console.WriteLine("PASS "+name);}
void Throws(Action a,string name){bool caught=false;try{a();}catch(Exception e)when(e is InvalidDataException or InvalidOperationException or IOException){caught=true;}Check(caught,name);}
var temp=Path.Combine(Path.GetTempPath(),"mcd2-installer-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(temp);
try {
 byte[] file=Encoding.UTF8.GetBytes("qualified test payload");string hash=InstallerEngine.Digest(file);var own=new Dictionary<string,string>{{"Dungeons/Binaries/Win64/mcd2-graphics.addon64",hash}};
 var dependencies=new Dictionary<string,object>{["ReShade"]=new{version="test",file="Dungeons/Binaries/Win64/dxgi.dll",sha256=hash,url="https://reshade.me/"},["RenoDXUEExtended"]=new{version="test",file="Dungeons/Binaries/Win64/renodx-ue-extended.addon64",sha256=hash,url="https://github.com/marat569/renodx"},["DLSSRuntime"]=new{version="test",file=InstallerEngine.Runtime,sha256=hash,url="https://github.com/NVIDIA/DLSS"}};
 string lockJson=JsonSerializer.Serialize(new{game=new{steamBuildID="123",exeSHA256=hash},dependencies});
 var manifest=JsonSerializer.Serialize(new{version="candidate.test",files=own});
 byte[] Payload(){using var memory=new MemoryStream();using(var z=new ZipArchive(memory,ZipArchiveMode.Create,true)){using var s=z.CreateEntry(own.Keys.Single()).Open();s.Write(file);}return memory.ToArray();}
 InstallerEngine Engine(Func<Stream?>? payload=null){var e=new InstallerEngine(lockJson,manifest,payload??(()=>new MemoryStream(Payload())));e.RequireClosed=()=>{};e.ConfigRootOverride=Path.Combine(temp,"Config");e.SetGame(temp);return e;}
 void Put(string path,byte[]? bytes=null){var p=Path.Combine(temp,path);Directory.CreateDirectory(Path.GetDirectoryName(p)!);File.WriteAllBytes(p,bytes??file);}
 Put(InstallerEngine.Shipping);Put("Dungeons/Binaries/Win64/dxgi.dll");Put("Dungeons/Binaries/Win64/renodx-ue-extended.addon64");
 var runtime=Path.Combine(temp,"download.dll");File.WriteAllBytes(runtime,file);
 var e=Engine();Check(!e.Ready,"Missing runtime prevents installation");e.SelectDependency("DLSSRuntime",runtime);Check(e.Ready,"Selected hash verified runtime makes install ready");
 e.Install();Check(InstallerEngine.DigestFile(Path.Combine(temp,own.Keys.Single()))==hash,"Payload installed and hashed");
 Check(File.ReadAllText(Path.Combine(temp,InstallerEngine.Marker)).Contains("candidate.test"),"Candidate version recorded");
 Throws(()=>e.Install(),"Duplicate install refused");
 Put(own.Keys.Single(),Encoding.UTF8.GetBytes("modified"));Throws(()=>e.Uninstall(),"Modified file stops uninstall before mutation");Throws(()=>e.Install(true),"Modified file stops repair");Check(File.Exists(Path.Combine(temp,InstallerEngine.Runtime)),"Runtime retained after failed uninstall");
 Put(own.Keys.Single());File.Delete(Path.Combine(temp,own.Keys.Single()));e.Install(true);Check(File.Exists(Path.Combine(temp,own.Keys.Single())),"Missing owned file repaired");
 var report=e.DiagnosticReport();Check(!report.Contains(temp)&&!report.Contains(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)),"Report excludes private paths");
 e.Uninstall();Check(!File.Exists(Path.Combine(temp,own.Keys.Single()))&&!File.Exists(Path.Combine(temp,InstallerEngine.Runtime)),"Own payload and runtime removed");Check(File.Exists(Path.Combine(temp,"Dungeons/Binaries/Win64/dxgi.dll")),"External dependency preserved");
 Throws(()=>InstallerEngine.Target(temp,"../outside"),"Traversal rejected");Throws(()=>InstallerEngine.Target(temp,"C:/absolute"),"Drive path rejected");Throws(()=>InstallerEngine.Target(temp,"a\\b"),"Backslash archive path rejected");
 var evil=Engine(()=>new MemoryStream(Encoding.UTF8.GetBytes("broken zip")));evil.SelectDependency("DLSSRuntime",runtime);Throws(()=>evil.Install(),"Broken package refused before writing");Check(!File.Exists(Path.Combine(temp,InstallerEngine.Marker)),"Failed install leaves no receipt");
 var blocked=Engine();blocked.RequireClosed=()=>throw new InvalidOperationException("Running game");Throws(()=>blocked.SelectDependency("DLSSRuntime",runtime),"Running game blocks dependency selection");
 // HDR bootstrap preserves unrelated lines and restores just its owned key.
 var config=Path.Combine(temp,"Config/UserEngine.ini");Directory.CreateDirectory(Path.GetDirectoryName(config)!);File.WriteAllText(config,"[SystemSettings]\nOther=keep\nr.AllowHDR=0\n[Elsewhere]\nValue=keep\n");
 var hdr=Engine();hdr.SelectDependency("DLSSRuntime",runtime);hdr.Install();Check(File.ReadAllText(config).Contains("r.AllowHDR=1")&&File.ReadAllText(config).Contains("Other=keep"),"HDR bootstrap changes only owned key");hdr.Uninstall();Check(File.ReadAllText(config).Contains("r.AllowHDR=0")&&File.ReadAllText(config).Contains("Value=keep"),"HDR uninstall restores previous value");
 hdr=Engine();hdr.SelectDependency("DLSSRuntime",runtime);hdr.Install();File.WriteAllText(config,File.ReadAllText(config).Replace("r.AllowHDR=1","r.AllowHDR=0"));Check(hdr.Scan().Single(x=>x.Name=="Graphics mod payload").State!="OK","Verify detects edited HDR bootstrap");Throws(()=>hdr.Install(true),"Edited HDR bootstrap blocks repair without overwrite");hdr.Uninstall();Check(File.ReadAllText(config).Contains("r.AllowHDR=0"),"Uninstall retains edited HDR setting");
 File.WriteAllText(config,"[SystemSettings]\nr.AllowHDR=0\nr.AllowHDR=1\n");hdr=Engine();hdr.SelectDependency("DLSSRuntime",runtime);Throws(()=>hdr.Install(),"Duplicate HDR key refused");Check(!File.Exists(Path.Combine(temp,own.Keys.Single()))&&!File.Exists(Path.Combine(temp,InstallerEngine.Marker)),"Configuration failure rolls back payload and receipt");File.Delete(config);
 // Fresh/default renderer configuration must supply the TAA boundary for SR.
 File.WriteAllText(config,"[SystemSettings]\nr.AntiAliasingMethod=4\nOther=keep\n");hdr=Engine();hdr.SelectDependency("DLSSRuntime",runtime);hdr.Install();Check(File.ReadAllText(config).Contains("r.AntiAliasingMethod=2")&&File.ReadAllText(config).Contains("Other=keep"),"Temporal AA bootstrap preserves unrelated settings");hdr.Uninstall();Check(File.ReadAllText(config).Contains("r.AntiAliasingMethod=4")&&!File.ReadAllText(config).Contains("r.AllowHDR"),"Uninstall restores previous AA and removes added HDR");
 hdr=Engine();hdr.SelectDependency("DLSSRuntime",runtime);hdr.Install();File.WriteAllText(config,File.ReadAllText(config).Replace("r.AntiAliasingMethod=2","r.AntiAliasingMethod=3"));Throws(()=>hdr.Install(true),"Edited AA bootstrap blocks repair");hdr.Uninstall();Check(File.ReadAllText(config).Contains("r.AntiAliasingMethod=3"),"Uninstall retains edited AA");File.Delete(config);
 // Steam discovery includes additional modern and legacy VDF libraries.
 var steam=Path.Combine(temp,"Steam");Directory.CreateDirectory(Path.Combine(steam,"steamapps"));var lib=Path.Combine(temp,"Library");var game=Path.GetFullPath(Path.Combine(lib,"steamapps/common/Minecraft Dungeons II"));Directory.CreateDirectory(Path.GetDirectoryName(Path.Combine(game,InstallerEngine.Shipping))!);File.WriteAllBytes(Path.Combine(game,InstallerEngine.Shipping),file);File.WriteAllText(Path.Combine(steam,"steamapps/libraryfolders.vdf"),"\"libraryfolders\" { \"1\" { \"path\" \""+lib.Replace("\\","\\\\")+"\" } }");Check(InstallerEngine.DetectGames(new[]{steam}).Contains(game),"Modern Steam library detected");File.WriteAllText(Path.Combine(steam,"steamapps/libraryfolders.vdf"),"\"1\" \""+lib.Replace("\\","\\\\")+"\"");Check(InstallerEngine.DetectGames(new[]{steam}).Contains(game),"Legacy Steam library detected");
 // Known dependency upgrades require exact previous hashes and retain recovery bytes.
 var oldBytes=Encoding.UTF8.GetBytes("qualified previous dependency");var oldHash=InstallerEngine.Digest(oldBytes);var deps2=new Dictionary<string,object>(dependencies);string pathA="Dungeons/Content/Paks/~mods/BlueprintLoader/a.pak",pathB="Dungeons/Content/Paks/~mods/BlueprintLoader/b.utoc";
 byte[] MakeZip(params string[] names){using var m=new MemoryStream();using(var z=new ZipArchive(m,ZipArchiveMode.Create,true))foreach(var name in names){using var entry=z.CreateEntry(name).Open();entry.Write(file);}return m.ToArray();}
 var archive=MakeZip("BlueprintLoader/a.pak","BlueprintLoader/b.utoc");deps2["BlueprintLoader"]=new{version="2.0",files=new Dictionary<string,string>{{pathA,hash},{pathB,hash}},upgradeFromFiles=new Dictionary<string,string>{{pathA,oldHash},{pathB,oldHash}},archiveSHA256=InstallerEngine.Digest(archive),url="https://www.nexusmods.com/minecraftdungeons2/mods/2"};
 var lock2=JsonSerializer.Serialize(new{game=new{steamBuildID="123",exeSHA256=hash},dependencies=deps2});var zipFile=Path.Combine(temp,"loader.zip");File.WriteAllBytes(zipFile,archive);Put(pathA,oldBytes);Put(pathB,oldBytes);
 var upgrade=new InstallerEngine(lock2,manifest,()=>new MemoryStream(Payload())){RequireClosed=()=>{},ConfigRootOverride=Path.Combine(temp,"Config")};upgrade.SetGame(temp);upgrade.SelectDependency("DLSSRuntime",runtime);upgrade.SelectDependency("BlueprintLoader",zipFile);upgrade.Install();Check(InstallerEngine.DigestFile(Path.Combine(temp,pathA))==hash,"Known Blueprint dependency upgraded");Check(InstallerEngine.DigestFile(Path.Combine(temp,"Dungeons/Binaries/Win64/MCD2GraphicsDependencyBackups/"+oldHash+".bak"))==oldHash,"Dependency recovery hash retained");upgrade.Uninstall();Check(File.Exists(Path.Combine(temp,pathA)),"Upgraded external dependency retained on uninstall");
 Put(pathA,Encoding.UTF8.GetBytes("unknown change"));Throws(()=>upgrade.SelectDependency("BlueprintLoader",zipFile),"Unknown dependency not overwritten");
 var unsafeZip=MakeZip("../a.pak","b.utoc");deps2["BlueprintLoader"]=new{version="2.0",files=new Dictionary<string,string>{{pathA,hash},{pathB,hash}},archiveSHA256=InstallerEngine.Digest(unsafeZip),url="https://www.nexusmods.com/minecraftdungeons2/mods/2"};var unsafeLock=JsonSerializer.Serialize(new{game=new{steamBuildID="123",exeSHA256=hash},dependencies=deps2});var unsafeEngine=new InstallerEngine(unsafeLock,manifest,()=>new MemoryStream(Payload())){RequireClosed=()=>{}};unsafeEngine.SetGame(temp);File.WriteAllBytes(zipFile,unsafeZip);Throws(()=>unsafeEngine.SelectDependency("BlueprintLoader",zipFile),"Archive traversal refused before extraction");
 // Older qualified receipts upgrade through repair; arbitrary receipt hashes do not grant ownership.
 var oldManifest=new Dictionary<string,string>(own){{InstallerEngine.Runtime,hash}};Put(own.Keys.Single());Put(InstallerEngine.Runtime);Put(InstallerEngine.Marker,Encoding.UTF8.GetBytes(JsonSerializer.Serialize(new{version="previous.test",files=oldManifest})));var withOld=JsonSerializer.Serialize(new{version="candidate.test",files=own,upgradeFrom=new Dictionary<string,Dictionary<string,string>>{{"previous.test",oldManifest}}});var migration=new InstallerEngine(lockJson,withOld,()=>new MemoryStream(Payload())){RequireClosed=()=>{},ConfigRootOverride=Path.Combine(temp,"Config")};migration.SetGame(temp);migration.Install(true);Check(File.ReadAllText(Path.Combine(temp,InstallerEngine.Marker)).Contains("candidate.test"),"Qualified previous receipt migrated");migration.Uninstall();Put(InstallerEngine.Marker,Encoding.UTF8.GetBytes(JsonSerializer.Serialize(new{version="candidate.test",files=new Dictionary<string,string>{{own.Keys.Single(),oldHash},{InstallerEngine.Runtime,hash}}})));Throws(()=>migration.Uninstall(),"Unqualified receipt hash does not grant ownership");Check(migration.Scan().Single(x=>x.Name=="Graphics mod payload").State!="OK","Verify rejects unqualified receipt");

}finally{Directory.Delete(temp,true);}
Console.WriteLine($"{cases} checks passed");
