list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES WINDOWS_SYSROOT)
if(NOT DEFINED WINDOWS_SYSROOT)
  message(FATAL_ERROR "Set WINDOWS_SYSROOT to licensed Microsoft CRT/SDK files")
endif()
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_COMPILER clang-cl)
set(CMAKE_CXX_COMPILER clang-cl)
set(CMAKE_LINKER lld-link)
set(CMAKE_AR llvm-lib)
set(CMAKE_RC_COMPILER llvm-rc)
set(CMAKE_MT llvm-mt)
set(CMAKE_C_FLAGS_INIT "/imsvc\"${WINDOWS_SYSROOT}/crt/include\" /imsvc\"${WINDOWS_SYSROOT}/sdk/include/ucrt\" /imsvc\"${WINDOWS_SYSROOT}/sdk/include/shared\" /imsvc\"${WINDOWS_SYSROOT}/sdk/include/um\" /imsvc\"${WINDOWS_SYSROOT}/sdk/include/winrt\" /clang:-fms-compatibility-version=19.44")
set(CMAKE_CXX_FLAGS_INIT "/imsvc\"${WINDOWS_SYSROOT}/crt/include\" /imsvc\"${WINDOWS_SYSROOT}/sdk/include/ucrt\" /imsvc\"${WINDOWS_SYSROOT}/sdk/include/shared\" /imsvc\"${WINDOWS_SYSROOT}/sdk/include/um\" /imsvc\"${WINDOWS_SYSROOT}/sdk/include/winrt\" /clang:-fms-compatibility-version=19.44")
set(CMAKE_EXE_LINKER_FLAGS_INIT "/libpath:\"${WINDOWS_SYSROOT}/crt/lib/x86_64\" /libpath:\"${WINDOWS_SYSROOT}/sdk/lib/ucrt/x86_64\" /libpath:\"${WINDOWS_SYSROOT}/sdk/lib/um/x86_64\"")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "/libpath:\"${WINDOWS_SYSROOT}/crt/lib/x86_64\" /libpath:\"${WINDOWS_SYSROOT}/sdk/lib/ucrt/x86_64\" /libpath:\"${WINDOWS_SYSROOT}/sdk/lib/um/x86_64\"")
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded CACHE STRING "" FORCE)
set(CMAKE_RC_FLAGS_INIT "/C65001 /I\"${WINDOWS_SYSROOT}/sdk/include/um\" /I\"${WINDOWS_SYSROOT}/sdk/include/shared\" /I\"${WINDOWS_SYSROOT}/crt/include\" /I\"${WINDOWS_SYSROOT}/sdk/include/ucrt\"")
