<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Reference Include="NeoRune.Assets"><HintPath>$(NeoRuneSdk)/tools/NeoRune.Assets.dll</HintPath></Reference><Reference Include="UAssetAPI"><HintPath>$(NeoRuneSdk)/tools/UAssetAPI.dll</HintPath></Reference><Reference Include="Newtonsoft.Json"><HintPath>$(NeoRuneSdk)/tools/Newtonsoft.Json.dll</HintPath></Reference><Reference Include="NeoRune.Packaging"><HintPath>$(NeoRuneSdk)/tools/NeoRune.Packaging.dll</HintPath></Reference></ItemGroup></Project>
